name: Torrent to Gofile

on:
  workflow_dispatch:
    inputs:
      torrent_link:
        description: 'Magnet Link or .torrent HTTP(S) URL to download'
        required: true
        type: string
      compress_before_upload:
        description: 'Compress the downloaded files into a zip archive before uploading to Gofile'
        required: false
        type: boolean
        default: false
      max_concurrent_uploads:
        description: 'Maximum number of concurrent uploads when uploading uncompressed files'
        required: false
        type: number
        default: 5

      message_id:
        description: 'Telegram Message ID to edit for progress updates'
        required: false
        type: string

jobs:
  download_and_upload:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install aria2
        run: choco install aria2 -y

      - name: Check disk space and download
        shell: powershell
        env:
          CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          MESSAGE_ID: ${{ github.event.inputs.message_id }}
          CALLBACK_SECRET: ${{ secrets.CALLBACK_SECRET }}
        run: .\scripts\check_and_download.ps1 -TorrentLink "${{ github.event.inputs.torrent_link }}" -WebhookUrl "${{ secrets.WEBHOOK_LINK }}" -ChatId "$env:CHAT_ID" -MessageId "$env:MESSAGE_ID"
        
      - name: Upload to Gofile
        shell: powershell
        env:
          CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          MESSAGE_ID: ${{ github.event.inputs.message_id }}
          CALLBACK_SECRET: ${{ secrets.CALLBACK_SECRET }}
        run: .\scripts\upload-folder.ps1 -TargetFolder "D:\a\downloads" -Compress:$${{ github.event.inputs.compress_before_upload }} -WebhookUrl "${{ secrets.WEBHOOK_LINK }}" -MaxConcurrent ${{ github.event.inputs.max_concurrent_uploads }} -ChatId "$env:CHAT_ID" -MessageId "$env:MESSAGE_ID"
        
      - name: Upload Gofile link artifact
        uses: actions/upload-artifact@v4
        with:
          name: gofile-link
          path: gofile_link.txt

      - name: Notify on Failure
        if: failure()
        shell: powershell
        env:
          CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
          CALLBACK_SECRET: ${{ secrets.CALLBACK_SECRET }}
        run: .\scripts\notify.ps1 -WebhookUrl "${{ secrets.WEBHOOK_LINK }}" -Status "Error" -Message "GitHub Actions workflow failed! Check the [Actions Log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details." -ChatId "$env:CHAT_ID"
